// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: finance/book/book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/printfcoder/home/proto/common/page"
	response "github.com/printfcoder/home/proto/common/response"
	_ "github.com/printfcoder/home/proto/common/time"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Book service

type BookService interface {
	AddExpense(ctx context.Context, in *AddExpenseRequest, opts ...client.CallOption) (*response.Response, error)
	DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...client.CallOption) (*response.Response, error)
	UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...client.CallOption) (*response.Response, error)
	ListExpenses(ctx context.Context, in *ListExpensesRequest, opts ...client.CallOption) (*response.Response, error)
}

type bookService struct {
	c    client.Client
	name string
}

func NewBookService(name string, c client.Client) BookService {
	return &bookService{
		c:    c,
		name: name,
	}
}

func (c *bookService) AddExpense(ctx context.Context, in *AddExpenseRequest, opts ...client.CallOption) (*response.Response, error) {
	req := c.c.NewRequest(c.name, "Book.AddExpense", in)
	out := new(response.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, opts ...client.CallOption) (*response.Response, error) {
	req := c.c.NewRequest(c.name, "Book.DeleteExpense", in)
	out := new(response.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, opts ...client.CallOption) (*response.Response, error) {
	req := c.c.NewRequest(c.name, "Book.UpdateExpense", in)
	out := new(response.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) ListExpenses(ctx context.Context, in *ListExpensesRequest, opts ...client.CallOption) (*response.Response, error) {
	req := c.c.NewRequest(c.name, "Book.ListExpenses", in)
	out := new(response.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Book service

type BookHandler interface {
	AddExpense(context.Context, *AddExpenseRequest, *response.Response) error
	DeleteExpense(context.Context, *DeleteExpenseRequest, *response.Response) error
	UpdateExpense(context.Context, *UpdateExpenseRequest, *response.Response) error
	ListExpenses(context.Context, *ListExpensesRequest, *response.Response) error
}

func RegisterBookHandler(s server.Server, hdlr BookHandler, opts ...server.HandlerOption) error {
	type book interface {
		AddExpense(ctx context.Context, in *AddExpenseRequest, out *response.Response) error
		DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, out *response.Response) error
		UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, out *response.Response) error
		ListExpenses(ctx context.Context, in *ListExpensesRequest, out *response.Response) error
	}
	type Book struct {
		book
	}
	h := &bookHandler{hdlr}
	return s.Handle(s.NewHandler(&Book{h}, opts...))
}

type bookHandler struct {
	BookHandler
}

func (h *bookHandler) AddExpense(ctx context.Context, in *AddExpenseRequest, out *response.Response) error {
	return h.BookHandler.AddExpense(ctx, in, out)
}

func (h *bookHandler) DeleteExpense(ctx context.Context, in *DeleteExpenseRequest, out *response.Response) error {
	return h.BookHandler.DeleteExpense(ctx, in, out)
}

func (h *bookHandler) UpdateExpense(ctx context.Context, in *UpdateExpenseRequest, out *response.Response) error {
	return h.BookHandler.UpdateExpense(ctx, in, out)
}

func (h *bookHandler) ListExpenses(ctx context.Context, in *ListExpensesRequest, out *response.Response) error {
	return h.BookHandler.ListExpenses(ctx, in, out)
}
