// Code generated by protoc-gen-go. DO NOT EDIT.
// source: finance/book/book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	page "github.com/printfcoder/home/proto/common/page"
	_ "github.com/printfcoder/home/proto/common/response"
	time "github.com/printfcoder/home/proto/common/time"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Expense struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label                int64    `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
	Value                float32  `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	AccountType          string   `protobuf:"bytes,4,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Members              []int64  `protobuf:"varint,5,rep,packed,name=members,proto3" json:"members,omitempty"`
	Time                 int64    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expense) Reset()         { *m = Expense{} }
func (m *Expense) String() string { return proto.CompactTextString(m) }
func (*Expense) ProtoMessage()    {}
func (*Expense) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfc4e7a0c92f58d, []int{0}
}

func (m *Expense) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expense.Unmarshal(m, b)
}
func (m *Expense) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expense.Marshal(b, m, deterministic)
}
func (m *Expense) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expense.Merge(m, src)
}
func (m *Expense) XXX_Size() int {
	return xxx_messageInfo_Expense.Size(m)
}
func (m *Expense) XXX_DiscardUnknown() {
	xxx_messageInfo_Expense.DiscardUnknown(m)
}

var xxx_messageInfo_Expense proto.InternalMessageInfo

func (m *Expense) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Expense) GetLabel() int64 {
	if m != nil {
		return m.Label
	}
	return 0
}

func (m *Expense) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Expense) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *Expense) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Expense) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type NewExpenseRequest struct {
	Expense              *Expense `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewExpenseRequest) Reset()         { *m = NewExpenseRequest{} }
func (m *NewExpenseRequest) String() string { return proto.CompactTextString(m) }
func (*NewExpenseRequest) ProtoMessage()    {}
func (*NewExpenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfc4e7a0c92f58d, []int{1}
}

func (m *NewExpenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewExpenseRequest.Unmarshal(m, b)
}
func (m *NewExpenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewExpenseRequest.Marshal(b, m, deterministic)
}
func (m *NewExpenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewExpenseRequest.Merge(m, src)
}
func (m *NewExpenseRequest) XXX_Size() int {
	return xxx_messageInfo_NewExpenseRequest.Size(m)
}
func (m *NewExpenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewExpenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewExpenseRequest proto.InternalMessageInfo

func (m *NewExpenseRequest) GetExpense() *Expense {
	if m != nil {
		return m.Expense
	}
	return nil
}

type RemoveExpenseRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveExpenseRequest) Reset()         { *m = RemoveExpenseRequest{} }
func (m *RemoveExpenseRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveExpenseRequest) ProtoMessage()    {}
func (*RemoveExpenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfc4e7a0c92f58d, []int{2}
}

func (m *RemoveExpenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveExpenseRequest.Unmarshal(m, b)
}
func (m *RemoveExpenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveExpenseRequest.Marshal(b, m, deterministic)
}
func (m *RemoveExpenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveExpenseRequest.Merge(m, src)
}
func (m *RemoveExpenseRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveExpenseRequest.Size(m)
}
func (m *RemoveExpenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveExpenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveExpenseRequest proto.InternalMessageInfo

func (m *RemoveExpenseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateExpenseRequest struct {
	Expense              *Expense `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateExpenseRequest) Reset()         { *m = UpdateExpenseRequest{} }
func (m *UpdateExpenseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateExpenseRequest) ProtoMessage()    {}
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfc4e7a0c92f58d, []int{3}
}

func (m *UpdateExpenseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateExpenseRequest.Unmarshal(m, b)
}
func (m *UpdateExpenseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateExpenseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateExpenseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateExpenseRequest.Merge(m, src)
}
func (m *UpdateExpenseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateExpenseRequest.Size(m)
}
func (m *UpdateExpenseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateExpenseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateExpenseRequest proto.InternalMessageInfo

func (m *UpdateExpenseRequest) GetExpense() *Expense {
	if m != nil {
		return m.Expense
	}
	return nil
}

type ListExpensesRequest struct {
	Page                 *page.Page     `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	TimeSpan             *time.TimeSpan `protobuf:"bytes,2,opt,name=timeSpan,proto3" json:"timeSpan,omitempty"`
	Labels               []int64        `protobuf:"varint,3,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	AccountTypes         []string       `protobuf:"bytes,4,rep,name=accountTypes,proto3" json:"accountTypes,omitempty"`
	Members              []int64        `protobuf:"varint,5,rep,packed,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListExpensesRequest) Reset()         { *m = ListExpensesRequest{} }
func (m *ListExpensesRequest) String() string { return proto.CompactTextString(m) }
func (*ListExpensesRequest) ProtoMessage()    {}
func (*ListExpensesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acfc4e7a0c92f58d, []int{4}
}

func (m *ListExpensesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListExpensesRequest.Unmarshal(m, b)
}
func (m *ListExpensesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListExpensesRequest.Marshal(b, m, deterministic)
}
func (m *ListExpensesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListExpensesRequest.Merge(m, src)
}
func (m *ListExpensesRequest) XXX_Size() int {
	return xxx_messageInfo_ListExpensesRequest.Size(m)
}
func (m *ListExpensesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListExpensesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListExpensesRequest proto.InternalMessageInfo

func (m *ListExpensesRequest) GetPage() *page.Page {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListExpensesRequest) GetTimeSpan() *time.TimeSpan {
	if m != nil {
		return m.TimeSpan
	}
	return nil
}

func (m *ListExpensesRequest) GetLabels() []int64 {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ListExpensesRequest) GetAccountTypes() []string {
	if m != nil {
		return m.AccountTypes
	}
	return nil
}

func (m *ListExpensesRequest) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Expense)(nil), "Expense")
	proto.RegisterType((*NewExpenseRequest)(nil), "NewExpenseRequest")
	proto.RegisterType((*RemoveExpenseRequest)(nil), "RemoveExpenseRequest")
	proto.RegisterType((*UpdateExpenseRequest)(nil), "UpdateExpenseRequest")
	proto.RegisterType((*ListExpensesRequest)(nil), "ListExpensesRequest")
}

func init() { proto.RegisterFile("finance/book/book.proto", fileDescriptor_acfc4e7a0c92f58d) }

var fileDescriptor_acfc4e7a0c92f58d = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xec, 0x26, 0xed, 0xa4, 0x54, 0x62, 0x48, 0x61, 0xd5, 0x03, 0xb2, 0x7c, 0x40,
	0x16, 0x87, 0xb5, 0x14, 0x24, 0x40, 0x15, 0x07, 0x40, 0xe2, 0x86, 0x10, 0x5a, 0xca, 0x03, 0xac,
	0xed, 0x69, 0x6a, 0x35, 0xfb, 0x07, 0xef, 0xa6, 0xc0, 0x83, 0xf0, 0x2c, 0xbc, 0x19, 0x67, 0x94,
	0x8d, 0x1d, 0x25, 0x25, 0x91, 0xa0, 0x97, 0xd5, 0xcc, 0x37, 0xfb, 0xed, 0xee, 0xfc, 0x66, 0xe1,
	0xf1, 0x65, 0xa3, 0xa5, 0xae, 0xa8, 0x28, 0x8d, 0xb9, 0x0e, 0x0b, 0xb7, 0xad, 0xf1, 0xe6, 0xec,
	0xcd, 0xac, 0xf1, 0x57, 0x8b, 0x92, 0x57, 0x46, 0x15, 0xb6, 0x6d, 0xb4, 0xbf, 0xac, 0x4c, 0x4d,
	0x6d, 0x71, 0x65, 0x14, 0x15, 0x61, 0x4b, 0x51, 0x19, 0xa5, 0x8c, 0x2e, 0x5a, 0x72, 0xd6, 0x68,
	0x47, 0xeb, 0xa0, 0x3b, 0xe1, 0xd5, 0x3f, 0x9f, 0xe0, 0x1b, 0x45, 0x61, 0xf9, 0x6f, 0xa7, 0x95,
	0x33, 0x0a, 0xcb, 0xca, 0x99, 0xfd, 0x8c, 0x60, 0xf4, 0xfe, 0xbb, 0x25, 0xed, 0x08, 0x4f, 0x60,
	0xd0, 0xd4, 0x2c, 0x4a, 0xa3, 0x3c, 0x16, 0x83, 0xa6, 0xc6, 0x09, 0x1c, 0xcc, 0x65, 0x49, 0x73,
	0x36, 0x08, 0xd2, 0x2a, 0x59, 0xaa, 0x37, 0x72, 0xbe, 0x20, 0x16, 0xa7, 0x51, 0x3e, 0x10, 0xab,
	0x04, 0x53, 0x18, 0xcb, 0xaa, 0x32, 0x0b, 0xed, 0x2f, 0x7e, 0x58, 0x62, 0x49, 0x1a, 0xe5, 0x47,
	0x62, 0x53, 0x42, 0x06, 0x23, 0x45, 0xaa, 0xa4, 0xd6, 0xb1, 0x83, 0x34, 0xce, 0x63, 0xd1, 0xa7,
	0x88, 0x90, 0x2c, 0x7b, 0x61, 0xc3, 0x70, 0x4d, 0x88, 0xb3, 0x97, 0xf0, 0xe0, 0x23, 0x7d, 0xeb,
	0x5e, 0x26, 0xe8, 0xeb, 0x82, 0x9c, 0xc7, 0x0c, 0x46, 0xb4, 0x52, 0xc2, 0x2b, 0xc7, 0xd3, 0x43,
	0xde, 0xef, 0xe8, 0x0b, 0xd9, 0x53, 0x98, 0x08, 0x52, 0xe6, 0x86, 0x6e, 0x79, 0x6f, 0x35, 0x97,
	0x9d, 0xc3, 0xe4, 0x8b, 0xad, 0xa5, 0xa7, 0x3b, 0xdc, 0xf1, 0x2b, 0x82, 0x87, 0x1f, 0x1a, 0xe7,
	0xbb, 0x82, 0xeb, 0xbd, 0x4f, 0x20, 0x59, 0xa2, 0xed, 0x8c, 0xc0, 0x03, 0xe7, 0x4f, 0x72, 0x46,
	0x22, 0xe8, 0xf8, 0x0c, 0x0e, 0x97, 0xcd, 0x7d, 0xb6, 0x52, 0x07, 0xa6, 0xe3, 0xe9, 0x09, 0x0f,
	0x53, 0xbc, 0xe8, 0x54, 0xb1, 0xae, 0xe3, 0x23, 0x18, 0x06, 0xde, 0x8e, 0xc5, 0x81, 0x56, 0x97,
	0x61, 0x06, 0xc7, 0x1b, 0x54, 0x1d, 0x4b, 0xd2, 0x38, 0x3f, 0x12, 0x5b, 0xda, 0x7e, 0xd4, 0xd3,
	0xdf, 0x11, 0x24, 0xef, 0x8c, 0xb9, 0xc6, 0x17, 0x00, 0x6f, 0xeb, 0xba, 0x9f, 0x3c, 0xf2, 0xbf,
	0x60, 0x9f, 0x21, 0x5f, 0x7f, 0x4f, 0xd1, 0x05, 0xd9, 0x3d, 0x7c, 0x0d, 0xf7, 0xb7, 0xf0, 0xe2,
	0x29, 0xdf, 0x85, 0x7b, 0xbf, 0x7b, 0x0b, 0x3a, 0x9e, 0xf2, 0x5d, 0x43, 0xd8, 0xe3, 0x3e, 0x87,
	0xe3, 0x4d, 0xea, 0x38, 0xe1, 0x3b, 0x86, 0xb0, 0xdb, 0x5b, 0x0e, 0xc3, 0x77, 0x7f, 0xfe, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x69, 0x8c, 0xc0, 0xbf, 0x03, 0x00, 0x00,
}
