// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: finance/book/book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	response "github.com/printfcoder/home/proto/common/response"
	_ "github.com/printfcoder/home/proto/common/time"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	AddExpense(ctx context.Context, in *NewExpenseRequest, opts ...client.CallOption) (*response.Response, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) AddExpense(ctx context.Context, in *NewExpenseRequest, opts ...client.CallOption) (*response.Response, error) {
	req := c.c.NewRequest(c.name, "User.AddExpense", in)
	out := new(response.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	AddExpense(context.Context, *NewExpenseRequest, *response.Response) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		AddExpense(ctx context.Context, in *NewExpenseRequest, out *response.Response) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) AddExpense(ctx context.Context, in *NewExpenseRequest, out *response.Response) error {
	return h.UserHandler.AddExpense(ctx, in, out)
}
